language: python

cache: pip

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - "3.5-dev"
  - "nightly"

install:
  - pip install -r requirements.txt
  - pip install coveralls codecov
  - python setup.py install

script: nosetests --with-coverage

after_success:
    - codecov
    - coveralls
